export const PRODUCT_CATEGORIES = [
  "گرانیت",
  "ماربل",
  "اونیکس",
  "تراورتن",
  "کوارتزیت",
  "بازالت",
  "لایم‌استون",
  "سنگ نیمه‌قیمتی",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export type Product = {
  id: number;
  code: string;
  /** English URL slug — the product's public address (/products/<slug>) */
  slug: string;
  name: string;
  cat: string;
  stoneType?: string;
  size: string;
  image: string;
  heroImage: string;
  detailImage: string;
  finish: string;
  origin: string;
  colors: string;
  description?: string;
};

export const PRODUCTS: Product[] = [
  {
    "id": 1,
    "code": "KK-C-101",
    "slug": "persian-bianco",
    "name": "پرشین بیانکو",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "285 × 185",
    "image": "images/stones/chini-bianco.webp",
    "heroImage": "images/stones/chini-bianco.webp",
    "detailImage": "images/stones/chini-bianco-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، خاکستری",
    "description": "سنگ کریستال (چینی) ایرانی باکیفیت عالی و رگه‌های خاکستری روشن، بسیار محبوب برای سنگفرش و دکوراسیون داخلی."
  },
  {
    "id": 2,
    "code": "KK-G-102",
    "slug": "persian-zebra",
    "name": "پرشین زبرا",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۰۰ × ۱۸۰",
    "image": "images/prod_img_1.jpg",
    "heroImage": "images/inprod_img_1.jpg",
    "detailImage": "images/inprod_img_2.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "مشکی، سفید",
    "description": "گرانیت مشکی بسیار با‌دوام با خطوط سفید، مناسب برای فضاهای داخلی و خارجی، صفحه کابینت آشپزخانه و سرویس‌های بهداشتی."
  },
  {
    "id": 3,
    "code": "KK-G-103",
    "slug": "native-black-super-rock",
    "name": "نیتیو بلک سوپر راک",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۲۸۵ × ۱۶۰",
    "image": "images/stones/native-black.webp",
    "heroImage": "images/stones/native-black.webp",
    "detailImage": "images/stones/native-black-detail.webp",
    "finish": "بافت صخره‌ای / سه‌بعدی",
    "origin": "ایرانی",
    "colors": "مشکی",
    "description": "فرآوری‌شده با طرح صخره‌ای که بافت سه‌بعدی و اشکال هندسی کریستالی متمایزی ایجاد می‌کند و انعکاس نور خیره‌کننده‌ای دارد."
  },
  {
    "id": 4,
    "code": "KK-G-104",
    "slug": "tuyserkan",
    "name": "تویسرکان",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "311 × 161",
    "image": "images/stones/tuyserkan.webp",
    "heroImage": "images/stones/tuyserkan.webp",
    "detailImage": "images/stones/tuyserkan-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "مشکی، خاکستری تیره",
    "description": "گرانیت ایرانی مقاوم در برابر مواد شیمیایی، ایده‌آل برای دیوارهای داخلی، پله‌ها، کف حیاط، پارکینگ و نمای ساختمان."
  },
  {
    "id": 5,
    "code": "KK-Q-105",
    "slug": "black-horse-rock",
    "name": "بلک هورس راک",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۲۰ × ۱۹۰",
    "image": "images/stones/black-horse-rock.webp",
    "heroImage": "images/stones/black-horse-rock.webp",
    "detailImage": "images/stones/black-horse-rock-detail.webp",
    "finish": "بافت صخره‌ای",
    "origin": "برزیلی",
    "colors": "مشکی، خاکستری، سفید",
    "description": "کوارتزیت برزیلی فرآوری‌شده با طرح صخره‌ای همراه با بافت سه‌بعدی و هندسه کریستالی که انعکاس نور خیره‌کننده‌ای ارائه می‌دهد."
  },
  {
    "id": 6,
    "code": "KK-C-106",
    "slug": "silver-stream-rock",
    "name": "سیلور استریم راک",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "267 × 180",
    "image": "images/stones/silver-stream-rock.webp",
    "heroImage": "images/stones/silver-stream-rock.webp",
    "detailImage": "images/stones/silver-stream-rock-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "خاکستری، نقره‌ای، خاکستری روشن",
    "description": "ترکیبی چشم‌نواز از سایه‌های تیره و روشن. ساب‌پذیری بالا، مقاومت فشاری و سایشی عالی. فوق‌العاده برای طرح‌های بوک‌مچ و فور‌مچ."
  },
  {
    "id": 7,
    "code": "KK-G-107",
    "slug": "leathered-matrix",
    "name": "لدرد ماتریکس",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۲۰۹ × ۱۷۱",
    "image": "images/stones/leathered-matrix.webp",
    "heroImage": "images/stones/leathered-matrix.webp",
    "detailImage": "images/stones/leathered-matrix-detail.webp",
    "finish": "متریکس / بافت سه‌بعدی",
    "origin": "ایرانی",
    "colors": "خاکستری، خاکستری تیره، مشکی",
    "description": "زمینه خاکستری با فرآوری متریکس. دارای بافت سطحی سه‌بعدی که ظاهری مدرن و حس طبیعی می‌بخشد. مناسب برای دیوارهای داخلی و خارجی، کف، نما و پله‌ها."
  },
  {
    "id": 8,
    "code": "KK-M-108",
    "slug": "turtle-venato",
    "name": "ترتل وناتو",
    "cat": "ماربل",
    "stoneType": "ماربل فسیلی",
    "size": "280 × 185",
    "image": "images/stones/turtle-venato.webp",
    "heroImage": "images/stones/turtle-venato.webp",
    "detailImage": "images/stones/turtle-venato-detail.webp",
    "finish": "هوند (مات) / صیقلی",
    "origin": "آفریقایی",
    "colors": "قهوه‌ای، بژ، خاکستری تیره",
    "description": "مرمر فسیلی با بافتی منحصر‌به‌فرد، کاملاً مناسب برای طراحی دکوراسیون داخلی."
  },
  {
    "id": 9,
    "code": "KK-C-109",
    "slug": "persian-maya",
    "name": "پرشین مایا",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "۲۸۵ × ۱۷۵",
    "image": "images/stones/persian-maya.webp",
    "heroImage": "images/stones/persian-maya.webp",
    "detailImage": "images/stones/persian-maya-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، خاکستری روشن",
    "description": "یکی از بهترین گزینه‌ها برای سنگفرش دکوراسیون داخلی."
  },
  {
    "id": 11,
    "code": "KK-G-111",
    "slug": "alpinus-granite",
    "name": "آلپینوس گرانیت",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۱۵ × ۱۸۵",
    "image": "images/prod_img_10.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "کرم، قهوه‌ای، مشکی",
    "description": "گرانیت با‌دوام مناسب برای کف، دیوارها، نمای خارجی، آشپزخانه و سرویس‌های بهداشتی."
  },
  {
    "id": 12,
    "code": "KK-T-112",
    "slug": "red-travertine",
    "name": "قرمز تراورتن",
    "cat": "تراورتن",
    "stoneType": "تراورتن",
    "size": "258 × 150",
    "image": "images/stones/red-travertine.webp",
    "heroImage": "images/stones/red-travertine.webp",
    "detailImage": "images/stones/red-travertine-detail.webp",
    "finish": "صیقلی / هوند (مات)",
    "origin": "ایرانی",
    "colors": "قرمز، آجرپزی (ترکوتا)",
    "description": "انتخابی محبوب در میان سازندگان برای نمای خارجی و طراحی‌های شاخص (اکسنت) داخلی."
  },
  {
    "id": 13,
    "code": "KK-C-113",
    "slug": "persian-panda",
    "name": "پرشین پاندا",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "۲۹۰ × ۱۸۰",
    "image": "images/prod_img_12.jpg",
    "heroImage": "images/inprod_img_1.jpg",
    "detailImage": "images/inprod_img_2.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، مشکی",
    "description": "طرح و رنگ خاص با ساب‌پذیری بالا. مناسب برای چیدمان‌های بوک‌مچ و فور‌مچ در فضاهای داخلی، راهپله‌ها و دیواره‌ها."
  },
  {
    "id": 14,
    "code": "KK-Q-114",
    "slug": "copacabana",
    "name": "کوپاکابانا",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۲۰ × ۱۹۵",
    "image": "images/prod_img_13.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "مشکی، سفید",
    "description": "سنگ مشکی با رگه‌های سفید موازی، قابل استفاده در هر بخش از ساختمان برای ایجاد جلوه‌ای متمایز."
  },
  {
    "id": 15,
    "code": "KK-M-115",
    "slug": "pietra-grey-lashtar",
    "name": "پیاترا گری (لاشتار)",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "۲۸۰ × ۱۷۰",
    "image": "images/prod_img_14.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "هوند (مات) / صیقلی",
    "origin": "ایرانی",
    "colors": "خاکستری، زغالی، رگه‌های سفید",
    "description": "مرمر کلاسیک ایرانی که از دیرباز مورد توجه صنعت ساختمان بوده و عمدتاً در طراحی داخلی استفاده می‌شود."
  },
  {
    "id": 16,
    "code": "KK-M-116",
    "slug": "3d-black",
    "name": "تری‌دی بلک",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "270 × 150",
    "image": "images/stones/3D-black.webp",
    "heroImage": "images/stones/3D-black.webp",
    "detailImage": "images/stones/3D-black-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "مشکی، سفید، طلایی",
    "description": "زمینه مشکی با رگه‌های سفید و بعضاً طلایی. ساب‌پذیری بالا، مقاومت فشاری خوب و جذب آب پایین."
  },
  {
    "id": 17,
    "code": "KK-Q-117",
    "slug": "red-collins",
    "name": "رد کالینز",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۱۰ × ۱۸۵",
    "image": "images/stones/red-collins.webp",
    "heroImage": "images/stones/red-collins.webp",
    "detailImage": "images/stones/red-collins-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "قرمز، چندرنگ",
    "description": "رنگ‌های زنده با مقاومت فوق‌العاده در برابر ساییدگی و شوینده‌های اسیدی. کاربرد متنوع در تمامی قسمت‌های ساختمان."
  },
  {
    "id": 18,
    "code": "KK-S-118",
    "slug": "royal-blackwood",
    "name": "رویال بلک وود",
    "cat": "سنگ نیمه‌قیمتی",
    "stoneType": "ابسیدین",
    "size": "۲۶۰ × ۱۵۰",
    "image": "images/stones/royal-blackwood.webp",
    "heroImage": "images/stones/royal-blackwood.webp",
    "detailImage": "images/stones/royal-blackwood-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "چینی",
    "colors": "مشکی، قهوه‌ای تیره",
    "description": "سنگ کمیاب ابسیدین با سختی بالا، ایده‌آل برای طراحی‌های داخلی لوکس."
  },
  {
    "id": 19,
    "code": "KK-G-119",
    "slug": "algae-hard",
    "name": "آلگی هارد",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۲۲ × ۱۸۰",
    "image": "images/stones/Algae-hard.webp",
    "heroImage": "images/stones/Algae-hard.webp",
    "detailImage": "images/stones/Algae-hard-detail.webp",
    "finish": "ساب سخت (Hard Polish)",
    "origin": "ایرانی",
    "colors": "سبز، سفید",
    "description": "گرانیت ایرانی با‌دوام، مناسب برای نما و دکوراسیون داخلی."
  },
  {
    "id": 20,
    "code": "KK-G-120",
    "slug": "algae-cotton",
    "name": "آلگی کاتن",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۲۰ × ۱۷۵",
    "image": "images/stones/algae-cotton.webp",
    "heroImage": "images/stones/algae-cotton.webp",
    "detailImage": "images/stones/algae-cotton-detail.webp",
    "finish": "بافت‌دار / کاتن (پنبه‌ای)",
    "origin": "ایرانی",
    "colors": "کرم، سبز",
    "description": "گرانیت فرآوری‌شده با ابزار خاص برای دست‌یابی به بافتی شبیه به پارچه. مناسب برای نماها و فضاهای داخلی."
  },
  {
    "id": 21,
    "code": "KK-Q-121",
    "slug": "infinity-gold",
    "name": "اینفینیتی گلد",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "250 × 180",
    "image": "images/stones/infinity-gold.webp",
    "heroImage": "images/stones/infinity-gold.webp",
    "detailImage": "images/stones/infinity-gold-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "طلایی، مشکی، خاکستری",
    "description": "کوارتزیت ایرانی مناسب برای نما، دکوراسیون داخلی، کف‌پوش و آشپزخانه."
  },
  {
    "id": 22,
    "code": "KK-C-122",
    "slug": "aligoudarz-crystal",
    "name": "الیگودرز کریستال",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "۲۹۰ × ۱۷۵",
    "image": "images/stones/aligoudarz.webp",
    "heroImage": "images/stones/aligoudarz.webp",
    "detailImage": "images/stones/aligoudarz-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، خاکستری روشن",
    "description": "سنگ کریستال با تم روشن و ساب‌پذیری عالی، که فضایی آرامش‌بخش به دکوراسیون داخلی می‌بخشد."
  },
  {
    "id": 23,
    "code": "KK-B-123",
    "slug": "black-basalt",
    "name": "بلک بازالت",
    "cat": "بازالت",
    "stoneType": "بازالت",
    "size": "۲۵۰ × ۱۴۰",
    "image": "images/prod_img_22.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "هوند / شیاردار (برش‌خورده)",
    "origin": "ایرانی",
    "colors": "مشکی، خاکستری تیره",
    "description": "سنگ آتشفشانی بسیار مقاوم مناسب برای نما و دکوراسیون داخلی. بافت متخلخل آن چسبندگی خوبی با ملات سیمان دارد. باید بدون بند نصب شود."
  },
  {
    "id": 24,
    "code": "KK-G-124",
    "slug": "natanz-leathered-black-granite-grade-a",
    "name": "نطنز چرمی بلک گرانیت (گرید A)",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "280 × 190",
    "image": "images/stones/natanz-leathered-black-granite-grade-a.webp",
    "heroImage": "images/stones/natanz-leathered-black-granite-grade-a.webp",
    "detailImage": "images/stones/natanz-leathered-black-granite-grade-a-detail.webp",
    "finish": "لدرد (چرمی)",
    "origin": "ایرانی",
    "colors": "مشکی",
    "description": "گرانیت با سختی بالا و مقاوم در برابر اسید. ایده‌آل برای آشپزخانه، سرویس بهداشتی، نمای خارجی و دکوراسیون داخلی."
  },
  {
    "id": 25,
    "code": "KK-C-125",
    "slug": "diamond-silk-crystal",
    "name": "دایموند سیلک کریستال",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "۲۷۰ × ۱۷۵",
    "image": "images/stones/diamond-silk-crystal.webp",
    "heroImage": "images/stones/diamond-silk-crystal.webp",
    "detailImage": "images/stones/diamond-silk-crystal-detail.webp",
    "finish": "سیلک / صیقلی",
    "origin": "ایرانی",
    "colors": "خاکستری، سفید",
    "description": "بافت کریستالی زیبا که زیر نورپردازی مانند جواهر می‌درخشد."
  },
  {
    "id": 26,
    "code": "KK-G-126",
    "slug": "white-natanz-lineal",
    "name": "وایت نطنز لینیال",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "300 × 135",
    "image": "images/stones/white-natanz-lineal.webp",
    "heroImage": "images/stones/white-natanz-lineal.webp",
    "detailImage": "images/stones/white-natanz-lineal-detail.webp",
    "finish": "لینیال (خطی)",
    "origin": "ایرانی",
    "colors": "سفید، خاکستری",
    "description": "گرانیت با بافت شیاردار خطی، عالی برای دکوراسیون داخلی و نماهای مدرن."
  },
  {
    "id": 27,
    "code": "KK-G-127",
    "slug": "birjand-leathered-green-granite",
    "name": "بیرجند لدرد گرین گرانیت",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۲۸۵ × ۱۷۰",
    "image": "images/prod_img_26.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "لدرد (چرمی)",
    "origin": "ایرانی",
    "colors": "سبز، سبز تیره",
    "description": "گرانیت سبز چرمی منحصر‌به‌فرد مناسب برای نماهای خارجی و دیوارهای دکوراتیو داخلی."
  },
  {
    "id": 28,
    "code": "KK-Q-128",
    "slug": "black-tempest",
    "name": "بلک تمپست",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۲۵ × ۱۹۵",
    "image": "images/stones/black-tempest-leathered.webp",
    "heroImage": "images/stones/black-tempest-leathered.webp",
    "detailImage": "images/stones/black-tempest-leathered-detail.webp",
    "finish": "لدرد (چرمی) / صیقلی",
    "origin": "برزیلی",
    "colors": "مشکی، خاکستری",
    "description": "کوارتزیت برزیلی مناسب برای آشپزخانه، نما و دکوراسیون داخلی لوکس."
  },
  {
    "id": 29,
    "code": "KK-Q-129",
    "slug": "oreo",
    "name": "اوریو",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "325 × 195",
    "image": "images/stones/oreo.webp",
    "heroImage": "images/stones/oreo.webp",
    "detailImage": "images/stones/oreo-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "طلایی، آبی، قهوه‌ای",
    "description": "کوارتزیت خاص برزیلی مناسب برای طراحی داخلی مدرن و نمای ساختمان."
  },
  {
    "id": 30,
    "code": "KK-C-130",
    "slug": "ichkat-blue",
    "name": "ایچکت بلو",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "۲۸۰ × ۱۶۵",
    "image": "images/prod_img_29.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "آبی، آبی روشن، خاکستری",
    "description": "سنگ کریستال آبی با کنتراست بالا که حس هنری متمایزی به فضاهای داخلی می‌بخشد."
  },
  {
    "id": 31,
    "code": "KK-C-131",
    "slug": "prada-crystal",
    "name": "پرادا کریستال",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "290 × 180",
    "image": "images/stones/prada.webp",
    "heroImage": "images/stones/prada.webp",
    "detailImage": "images/stones/prada-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "کرم، بژ روشن",
    "description": "سنگ کریستال کرم‌رنگ با خطوط ظریف موازی، طراحی‌شده عمدتاً برای دکوراسیون داخلی."
  },
  {
    "id": 32,
    "code": "KK-G-132",
    "slug": "black-beauty-lineal",
    "name": "بلک بیوتی لینیال",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۲۹۰ × ۱۹۰",
    "image": "images/stones/black-beauty-lineal.webp",
    "heroImage": "images/stones/black-beauty-lineal.webp",
    "detailImage": "images/stones/black-beauty-lineal-detail.webp",
    "finish": "لینیال (خطی)",
    "origin": "ایرانی",
    "colors": "مشکی، طلایی",
    "description": "گرانیت فوق‌العاده با‌دوام با طرح بافت‌دار خطی برای ظاهری مدرن. متمایزکننده نمای خارجی و طراحی‌های داخلی."
  },
  {
    "id": 33,
    "code": "KK-M-133",
    "slug": "persian-silk",
    "name": "پرشین سیلک",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "175 × 150",
    "image": "images/stones/persian-silk.webp",
    "heroImage": "images/stones/persian-silk.webp",
    "detailImage": "images/stones/persian-silk-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "خاکستری، خاکستری روشن",
    "description": "محبوب در بازارهای جهانی برای معماری مدرن. تم خاکستری شیک، آن را به انتخابی ایده‌آل برای طراحی داخلی تبدیل کرده است."
  },
  {
    "id": 34,
    "code": "KK-M-134",
    "slug": "marble-rose",
    "name": "ماربل رز",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "۲۶۰ × ۱۶۰",
    "image": "images/prod_img_33.jpg",
    "heroImage": "images/inprod_img_4.jpg",
    "detailImage": "images/inprod_img_5.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "صورتی، رز، هلویی",
    "description": "پالت رنگی متمایز در مقایسه با سایر مرمرهای بازار، برای خلق فضاهای داخلی جذاب."
  },
  {
    "id": 35,
    "code": "KK-G-135",
    "slug": "indian-black-forest",
    "name": "ایندیان بلک فورست",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "270 × 200",
    "image": "images/stones/black-forest.webp",
    "heroImage": "images/stones/black-forest.webp",
    "detailImage": "images/stones/black-forest-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "هندی",
    "colors": "مشکی، رگه‌های سفید",
    "description": "گرانیت باکیفیت عالی و مقاوم در برابر سایش و شوینده‌های اسیدی، مناسب برای تمامی کاربردهای داخلی و خارجی."
  },
  {
    "id": 36,
    "code": "KK-G-136",
    "slug": "volga-blue",
    "name": "ولگا بلو",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "328 × 200",
    "image": "images/stones/volga-blue.webp",
    "heroImage": "images/stones/volga-blue.webp",
    "detailImage": "images/stones/volga-blue-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "اوکراینی / وارداتی",
    "colors": "مشکی، لابرادوریت آبی",
    "description": "گرانیت شهرت‌یافته جهانی با درخشش آبی پررنگ در زمینه مشکی. بسیار مقاوم در برابر سایش و اسیدها."
  },
  {
    "id": 37,
    "code": "KK-G-137",
    "slug": "leathered-green-granite",
    "name": "لدرد گرین گرانیت",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "275 × 175",
    "image": "images/stones/leathered-green-granite.webp",
    "heroImage": "images/stones/leathered-green-granite.webp",
    "detailImage": "images/stones/leathered-green-granite-detail.webp",
    "finish": "لدرد (چرمی)",
    "origin": "ایرانی",
    "colors": "سبز",
    "description": "گرانیت سبز با فرآوری چرمی، بیانگر قدرت و لوکس بودن در نما و طراحی داخلی."
  },
  {
    "id": 38,
    "code": "KK-T-138",
    "slug": "cream-leathered-travertine",
    "name": "کریم لدرد تراورتن",
    "cat": "تراورتن",
    "stoneType": "تراورتن",
    "size": "220 × 170",
    "image": "images/stones/cream-leathered-travertine.webp",
    "heroImage": "images/stones/cream-leathered-travertine.webp",
    "detailImage": "images/stones/cream-leathered-travertine-detail.webp",
    "finish": "لدرد (چرمی)",
    "origin": "ایرانی",
    "colors": "کرم، بژ",
    "description": "پرکاربرد در طراحی‌های مینیمالیستی داخلی و خارجی، بخشنده زیبایی و آرامش تم کرم."
  },
  {
    "id": 39,
    "code": "KK-T-139",
    "slug": "cream-raw-vein-cut-travertine",
    "name": "کریم را وین-کات تراورتن",
    "cat": "تراورتن",
    "stoneType": "تراورتن",
    "size": "۲۷۵ × ۱۷۰",
    "image": "images/prod_img_38.jpg",
    "heroImage": "images/inprod_img_3.jpg",
    "detailImage": "images/inprod_img_4.jpg",
    "finish": "خام / بی‌موج (Vein-Cut)",
    "origin": "ایرانی",
    "colors": "کرم، استخوانی",
    "description": "تراورتن رزین‌نشده / خام برش‌خورده به صورت بی موج، محبوب برای نماها و فضاهای داخلی سبک مینیمال."
  },
  {
    "id": 40,
    "code": "KK-T-140",
    "slug": "tiramisu-travertine",
    "name": "تیرامیسو تراورتن",
    "cat": "تراورتن",
    "stoneType": "تراورتن",
    "size": "۲۸۰ × ۱۷۰",
    "image": "images/prod_img_39.jpg",
    "heroImage": "images/inprod_img_4.jpg",
    "detailImage": "images/inprod_img_5.jpg",
    "finish": "هوند (مات) / لدرد (چرمی)",
    "origin": "ایرانی",
    "colors": "کرم، قهوه‌ای گرم",
    "description": "تراورتن با رنگ‌های گرم برای طراحی‌های مدرن و مینیمال داخلی و خارجی."
  },
  {
    "id": 41,
    "code": "KK-G-141",
    "slug": "patagonia-black",
    "name": "پاتاگونیا بلک",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۳۰ × ۲۰۰",
    "image": "images/prod_img_40.jpg",
    "heroImage": "images/inprod_img_5.jpg",
    "detailImage": "images/inprod_img_0.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "مشکی، سفید، کوارتز شفاف",
    "description": "گرانیت فوق‌العاده کمیاب برزیلی با دانه کریستال‌های بسیار بزرگ که شبیه به هیچ سنگ دیگری در جهان نیست."
  },
  {
    "id": 42,
    "code": "KK-Q-142",
    "slug": "jacaranda",
    "name": "ژاکاراندا",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۱۰ × ۱۸۵",
    "image": "images/prod_img_41.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "چندرنگ، قرمز، طلایی، خاکستری",
    "description": "کوارتزیت خاص برزیلی با طرح‌های هنری و دانه‌های ریز کریستالی که زیر نور بسیار می‌درخشد."
  },
  {
    "id": 43,
    "code": "KK-G-143",
    "slug": "turquoise-granite",
    "name": "تورکواز گرانیت (فیروزه‌ای)",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "305 × 175",
    "image": "images/stones/turquoise-granite.webp",
    "heroImage": "images/stones/turquoise-granite.webp",
    "detailImage": "images/stones/turquoise-granite-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "فیروزه‌ای، آبی، سبز",
    "description": "گرانیت کمیاب آبی-فیروزه‌ای برای خلق عناصر شاخص و ویژه در طراحی داخلی."
  },
  {
    "id": 44,
    "code": "KK-M-144",
    "slug": "golden-olive",
    "name": "گولدن اولیو",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "۲۸۵ × ۱۷۵",
    "image": "images/prod_img_43.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "کرم، زیتونی، طلایی",
    "description": "مرمر یکدست کرم با هاله و رگه‌های ملایم زیتونی برای طراحی‌های داخلی گرم."
  },
  {
    "id": 45,
    "code": "KK-M-145",
    "slug": "persian-scato",
    "name": "پرشین اسکاتو",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "285 × 165",
    "image": "images/stones/chini-scato.webp",
    "heroImage": "images/stones/chini-scato.webp",
    "detailImage": "images/stones/chini-scato-detail.webp",
    "finish": "صیقلی / هوند (مات)",
    "origin": "ایرانی",
    "colors": "خاکستری، بژ",
    "description": "بافت و تم رنگی یکدست، بسیار مورد پسند در طراحی فضاهای مینیمال و معاصر."
  },
  {
    "id": 46,
    "code": "KK-C-146",
    "slug": "thassos-white",
    "name": "تاسوس وایت",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "270 × 150",
    "image": "images/stones/thassos.webp",
    "heroImage": "images/stones/thassos.webp",
    "detailImage": "images/stones/thassos-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "یونانی",
    "colors": "سفید خالص",
    "description": "یکی از سفیدترین سنگ‌های طبیعی در سطح جهان، بسیار ارزشمند برای طراحی داخلی و مجسمه‌سازی ظریف."
  },
  {
    "id": 47,
    "code": "KK-C-147",
    "slug": "jaguar-crystal",
    "name": "جگوار کریستال",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "260 × 175",
    "image": "images/stones/jaguar.webp",
    "heroImage": "images/stones/jaguar.webp",
    "detailImage": "images/stones/jaguar-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، مشکی، صورتی",
    "description": "بافت کریستالی متمایز که ترکیبی از رنگ‌های سفید، مشکی و صورتی است. محبوب برای فضاهای شاخص داخلی."
  },
  {
    "id": 48,
    "code": "KK-Q-148",
    "slug": "magma-gold",
    "name": "ماگما گلد",
    "cat": "کوارتزیت",
    "stoneType": "کوارتزیت",
    "size": "۳۲۵ × ۱۹۵",
    "image": "images/prod_img_47.jpg",
    "heroImage": "images/inprod_img_0.jpg",
    "detailImage": "images/inprod_img_1.jpg",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "برزیلی",
    "colors": "مشکی، طلایی، نارنجی",
    "description": "کوارتزیت لوکس برزیلی با رگه‌های چشمگیر طلایی و کهربایی."
  },
  {
    "id": 49,
    "code": "KK-G-149",
    "slug": "alpinus-rock",
    "name": "راک آلپینوس",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "295 × 158",
    "image": "images/stones/alpinus-rock.webp",
    "heroImage": "images/stones/alpinus-rock.webp",
    "detailImage": "images/stones/alpinus-rock-detail.webp",
    "finish": "بافت صخره‌ای / سه‌بعدی",
    "origin": "ایرانی",
    "colors": "کرم، قهوه‌ای، مشکی",
    "description": "گرانیت با دانه‌بندی درشت. فرآوری صخره‌ای برجستگی‌های کانی‌ها را به شکل برجسته‌کاری هندسی سه‌بعدی نمایان می‌سازد."
  },
  {
    "id": 50,
    "code": "KK-B-150",
    "slug": "light-mars-andesite",
    "name": "لایت مارس آندزیت",
    "cat": "بازالت",
    "stoneType": "آندزیت",
    "size": "۲۶۰ × ۱۵۰",
    "image": "images/prod_img_49.jpg",
    "heroImage": "images/inprod_img_2.jpg",
    "detailImage": "images/inprod_img_3.jpg",
    "finish": "هوند / مات",
    "origin": "ایرانی",
    "colors": "خاکستری بتنی، شیلی روشن",
    "description": "سنگ آتشفشانی بسیار مستحکم با بافت و ظاهری شبیه به بتن."
  },
  {
    "id": 51,
    "code": "KK-G-151",
    "slug": "matte-black-sea",
    "name": "مات بلک سی",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "۳۰۰ × ۱۸۰",
    "image": "images/stones/matte-blacksea.webp",
    "heroImage": "images/stones/matte-blacksea.webp",
    "detailImage": "images/stones/matte-blacksea-detail.webp",
    "finish": "مات / هوند",
    "origin": "ایرانی",
    "colors": "مشکی، سفید",
    "description": "گرانیت مشکی با رگه‌های سفید و کریستال‌های درخشان پنهان در زمینه مات، که جلوه‌ای لوکس ایجاد می‌کند."
  },
  {
    "id": 52,
    "code": "KK-G-152",
    "slug": "natanz-white-cotton",
    "name": "نطنز وایت کاتن",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "285 × 185",
    "image": "images/stones/cotton-natanz.webp",
    "heroImage": "images/stones/cotton-natanz.webp",
    "detailImage": "images/stones/cotton-natanz-detail.webp",
    "finish": "کاتن (پنبه‌ای)",
    "origin": "ایران",
    "colors": "سفید، خاکستری روشن",
    "description": "گرانیت سفید نطنز با بافتی تمیز و یکدست. ارتقایافته با فرآوری کاتن که ظاهری ظریف و ویژگی‌های سطحی ملایمی ارائه می‌دهد. مناسب برای فضاهای داخلی و خارجی از جمله کف، دیوار، نما، پله و..."
  },
  {
    "id": 53,
    "code": "KK-G-153",
    "slug": "natanz-white-scratch",
    "name": "نطنز وایت اسکرچ",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "270 × 160",
    "image": "images/stones/scratch-white-natanz.webp",
    "heroImage": "images/stones/scratch-white-natanz.webp",
    "detailImage": "images/stones/scratch-white-natanz-detail.webp",
    "finish": "اسکرچ (پنجه‌ای / شیاردار)",
    "origin": "ایران",
    "colors": "سفید، خاکستری روشن",
    "description": "گرانیت سفید نطنز با بافت یکدست و منظم. فرآوری‌شده با بافت اسکرچ که خطوط سطحی متمایزی ایجاد کرده و جلوه طبیعی آن را افزایش می‌دهد. مناسب برای کف، نما و فضاهای داخلی و خارجی."
  },
  {
    "id": 54,
    "code": "KK-M-154",
    "slug": "cream-marble-lineal",
    "name": "کریم ماربل لینیال",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "290 × 182",
    "image": "images/stones/cream-marble-lineal-plus.webp",
    "heroImage": "images/stones/cream-marble-lineal-plus.webp",
    "detailImage": "images/stones/cream-marble-lineal-plus-detail.webp",
    "finish": "لینیال (خطی)",
    "origin": "ایران",
    "colors": "کرم، بژ",
    "description": "مرمر کرم با بافت پاک و تمیز و تم رنگی گرم. فرآوری‌شده با طرح لینیال که ظاهری خطی و متمایز به آن بخشیده است. ایده‌آل برای کاربردهای داخلی شامل کف، دیوار و پله."
  },
  {
    "id": 55,
    "code": "KK-G-155",
    "slug": "leathered-black-diamond",
    "name": "لدرد بلک دایموند",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "285 × 190",
    "image": "images/stones/black-diamond-leather.webp",
    "heroImage": "images/stones/black-diamond-leather.webp",
    "detailImage": "images/stones/black-diamond-leather-detail.webp",
    "finish": "لدرد (چرمی)",
    "origin": "آنگولا",
    "colors": "مشکی، خاکستری تیره، کریستال سفید",
    "description": "گرانیت بلک دایموند آنگولا دارای زمینه مشکی جذاب با کریستال‌های طبیعی بزرگ. فرآوری چرمی بافت غنی و ظاهری شیک به همراه دوام فوق‌العاده ایجاد می‌کند. مناسب برای انواع کاربردهای داخلی و خارجی."
  },
  {
    "id": 56,
    "code": "KK-G-156",
    "slug": "tuyserkan-honed-granite",
    "name": "تویسرکان هوند گرانیت",
    "cat": "گرانیت",
    "stoneType": "گرانیت",
    "size": "333 × 170",
    "image": "images/stones/tuyserkan-honed-granite.webp",
    "heroImage": "images/stones/tuyserkan-honed-granite.webp",
    "detailImage": "images/stones/tuyserkan-honed-granite-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "مشکی، خاکستری تیره",
    "description": "گرانیت ایرانی مقاوم در برابر مواد شیمیایی، ایده‌آل برای دیوارهای داخلی، پله‌ها، کف حیاط، پارکینگ و نمای ساختمان."
  },
  {
    "id": 57,
    "code": "KK-M-157",
    "slug": "golden-rose",
    "name": "گلدن رز",
    "cat": "ماربل",
    "stoneType": "مرمر",
    "size": "270 × 155",
    "image": "images/stones/golden-rose.webp",
    "heroImage": "images/stones/golden-rose.webp",
    "detailImage": "images/stones/golden-rose-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایران",
    "colors": "قرمز، طلایی، رگه‌های سفید",
    "description": "مرمر گولدن رز دارای زمینه قرمز غنی همراه با رگه‌های شیک طلایی و سفید است. سطح صیقلی آن زیبایی طبیعی سنگ را برجسته‌تر می‌کند؛ انتخابی عالی برای فضاهای داخلی، پله‌ها و دیوارهای دکوراتیو."
  },
  {
    "id": 58,
    "code": "KK-C-158",
    "slug": "azna",
    "name": "ازنا",
    "cat": "ماربل",
    "stoneType": "کریستال",
    "size": "305 × 185",
    "image": "images/stones/chini-azna.webp",
    "heroImage": "images/stones/chini-azna.webp",
    "detailImage": "images/stones/chini-azna-detail.webp",
    "finish": "صیقلی (ساب‌خورده)",
    "origin": "ایرانی",
    "colors": "سفید، خاکستری روشن",
    "description": "یکی از عالی‌ترین گزینه‌ها برای سنگفرش فضاهای داخلی."
  }
];

export function getProduct(id: number): Product {
  return PRODUCTS.find(p => p.id === id) ?? PRODUCTS[0];
}

export function getProductBySlug(slug: string): Product | undefined {
  const s = slug.toLowerCase();
  return PRODUCTS.find(p => p.slug === s);
}

export function productSlug(id: number): string {
  return PRODUCTS.find(p => p.id === id)?.slug ?? String(id);
}

export type CategorySummary = { name: ProductCategory; count: number; image: string };

const CATEGORY_IMAGE_OVERRIDE: Partial<Record<ProductCategory, string>> = {
  "اونیکس": "images/onyx.webp",
  "لایم‌استون": "images/limestone.webp",
  "بازالت": "images/basalt.webp",
  "گرانیت": "images/stones/native-black.webp",
};

export const CATEGORY_SUMMARIES: CategorySummary[] = PRODUCT_CATEGORIES.map((cat) => {
  const items = PRODUCTS.filter((p) => p.cat === cat);
  return {
    name: cat,
    count: items.length,
    image: CATEGORY_IMAGE_OVERRIDE[cat] ?? items[0]?.image ?? "images/collections.jpg",
  };
});